#[derive(Debug)]
pub enum ControlCommand {
    Play,
    Stop,
    VolumeUp,
    VolumeDown,
    SetVolume(f32),
    Tune(String),
    TuneNext,
    TunePrev,
    SelectUp,
    SelectDown,
    Toggle,
    #[allow(dead_code)]
    TogglePause,
    #[allow(dead_code)]
    ToggleHelp,
    #[allow(dead_code)]
    ScrollHistoryUp,
    #[allow(dead_code)]
    ScrollHistoryDown,
    #[allow(dead_code)]
    Quit,
}